# A.2 HMM Forward and Backward Algorithm

The forward function can be declared like this: def forward(self, pX), and it should return the values alpha_hat and c. Additionally, you need to finish the logprob function in HMM.py;

The backward function can be declared like this: def backward(self, c, pX), and it should return beta_hat.

For more information, please refer to chapter A.3 and A.4 at the end of text book. You are required to implement and verify the algorithms according to these chapters of the text book. 

In [1]:
from PattRecClasses import DiscreteD, GaussD, HMM, MarkovChain
from matplotlib import pyplot as plt

import numpy as np

## A.2.1 Verify the implementation of forward algorithm

In [2]:
# HMM
q = np.array([1, 0])
A  = np.array([[0.9, 0.1, 0], [0, 0.9, 0.1 ]])
mc = MarkovChain(q, A) 

g1 = GaussD(means=[0], stdevs=[1])   # Distribution for state = 1
g2 = GaussD(means=[3], stdevs=[2])   # Distribution for state = 2
h  = HMM(mc, [g1, g2]) # The HMM

x = np.array([-0.2, 2.6, 1.3])

def compute_pX(x, distributions):
    
    T = x.shape[0]
    N = len(distributions)
    pX = np.zeros((N,T))

    for t in range(T):
        for j in range(N):
            pX[j,t] = distributions[j].prob(x[t])

    return pX

# Compute pX
pX = compute_pX(x, [g1, g2])

scaling_factor = np.sum(pX, axis=0, keepdims=True)

# Divide each element by the corresponding row sum
pX_scaled = pX / scaling_factor

# Call the forward method
alpha_hat, c = mc.forward(pX_scaled)

# Print the results
print("Scaled Forward Variables:")
print(alpha_hat)
print("Scaled Factors:")
print(c)

pX_scaled

Scaled Forward Variables:
[[1.         0.38470424 0.41887466]
 [0.         0.61529576 0.58112534]]
Scaled Factors:
[0.8757894  0.15196629 0.45640399 0.05811253]


array([[0.8757894 , 0.06495786, 0.55215885],
       [0.1242106 , 0.93504214, 0.44784115]])